[package]
name = "mosquitto-sys"
version = "0.1.0"
authors = ["Elie GÃ©nard <elaye.github.io@gmail.com>"]
description = "System bindings to libmosquitto"
license = "MIT"
build = "build.rs"
links = "mosquitto"

[build-dependencies]
bindgen = "0.26.3"